services:
  site:
    build: .
    container_name: site-evolucao
    ports:
      - "8082:80"
    volumes:
      - ./site-original:/var/www/html
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/"]
      interval: 10s
      timeout: 3s
      retries: 5

  site-v2:
    build:
      context: ./site-v2
    container_name: site-evolucao-v2
    ports:
      - "8083:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://127.0.0.1/"]
      interval: 10s
      timeout: 3s
      retries: 5
